### ISSUE TITLE
Upload package files for analysis

### ISSUE THREAD

**Issue by Jogai** [ServiceStackApps/TechStacks#1]
A cool feature would be that you can upload your package manager config file and it creates a list of used technologies to start with.

**Comment by mythz** [comment]
Wouldn't work for many reasons: would take a lot of effort to support each language/ecosystem package format, the list would only populate server libraries, we'd then need to support all client package formats to determine client packages and out of the hundreds of client/server package dependencies there would be only a handful that were instrumental enough to show on their page - the best way to determine that is the few seconds it would take someone to select tags from the autocomplete list.
