### ISSUE TITLE
Nomenclature

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStackApps/TechStacks#2]
Is there any particular reason for using the GetAll prefix for the names of some of the request DTOs in this project? Just curious.

**Comment by mythz** [comment]
No particlar reason, I just prefer it when the Service doesn't have any params and it's sole purpose is to return all results of a particular type, e.g:

```csharp
var allTechs = client.Get(new GetAllTechnologies());
```

But I'd drop the `All` if the Service had additional args that you could select which results to return, e.g:

```csharp
var techs = client.Get(new GetTechnologies { Ids = { 1, 2, 3 } });
```
