### ISSUE TITLE
Result/Results pattern

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStackApps/TechStacks#3]
Hi

Sorry for all the questions recently, I'm about to reach the point of no return in terms of making breaking changes to my API. I appreciate you taking the time to respond.

I'm interested in the Result/Results pattern in this project. It looks like an advantage of this is that dynamic clients can extract the result object from the response wrapper with less code. 

Is this something you'd recommend generally (for APIs consumed by 3rd parties)? Or only if the primary purpose is to provide a backend to a dynamic language like JavaScript? 

I notice that some response DTOs which return multiple types have been renamed back from Result to the type name like:

    public class GetTechnologyResponse
    {
        public DateTime Created { get; set; }

        public Technology Technology { get; set; }

        public List<TechnologyStack> TechnologyStacks { get; set; }

        public ResponseStatus ResponseStatus { get; set; }
    }

I guess my concern is if I define a response DTO like this:

    public class GetTechnologyResponse
    {
        public Technology Result { get; set; }
    }

If I later decide to also return the TechnologyStacks as well, I'd be making a breaking change, renaming Result to Technology. Otherwise if it wasn't renamed you'd end-up with `Result` and `TechnologyStacks` which is a bit strange, which is probably why it was [renamed ](https://github.com/ServiceStackApps/TechStacks/commit/66d906721cad994df1f0a9f2b6bd8916d93125ee)in TechStacks.

**Comment by mythz** [comment]
Hey sorry for the delay I just noticed this after scanning through the repos - probably best to ask questions like this in the Customer Forums so we don't miss them.

I think it's fine to start with `Result` then add in `TechnologyStacks` later when the Service needs to return more data later, e.g:

```csharp
public class GetTechnologyResponse
{
    public Technology Result { get; set; }
    public List<TechnologyStack> TechnologyStacks { get; set; }
}
```

Given the Service is called `GetTechnology` having a `Technology Result` is appropriate. I like using `Results` for plural and `Result` for single as the naming is predictable and leaves open the opportunity to be genericized later.
